name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build draft
      uses: martinthomson/i-d-template@v1
      with:
        make: build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: drafts
        path: "*.txt *.html"

    - name: Deploy to gh-pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        keep_files: false
